### ISSUE TITLE
It occur error when get GetNetInterface

### ISSUE THREAD

**Issue by eleens** [LINBIT/golinstor#12]
tag:v0.33.1
 When I use client.Nodes.GetNetInterface. I can't get the ret, and it occur errors with message "json: Unmarshal(non-pointer client.NetInterface)"

**Comment by rck** [comment]
Thanks for reporting. Should be fixed by Moritz in https://github.com/LINBIT/golinstor/commit/85ed9251081d7f4a7a5733229affc8881211b34a / v0.33.2
