### ISSUE TITLE
too many open file

### ISSUE THREAD

**Issue by eleens** [LINBIT/golinstor#13]
when I use this api to get node, this error is occur
Get \"http://192.168.1.11:3370/v1/nodes\": dial tcp 192.168.1.11:3370: socket: too many open files"

import (
	"fmt"
	"github.com/LINBIT/golinstor/client"
	"context"
	"net/url"
)

func ListNodes() ([]client.Node, error) {
	urls := "http://192.168.1.11:3370/v1/nodes"
	u, err := url.Parse(urls)
	if err != nil{
		return nil, err
	}

	c, err := client.NewClient(client.BaseURL(u))
	if err != nil {
		return nil, err
	}

	ctx := context.TODO()
	nodes, err := c.Nodes.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return nodes, nil
}

**Comment by rck** [comment]
can you please provide a *formatted* example that would at least compile? like having a `main` function for example... It took me some time to even get this malformed indentation.

also you don't point the client to `/v1/nodes`, you just point it to the controller, as shown in this [example](https://pkg.go.dev/github.com/LINBIT/golinstor/client#example-package-Simple)

**Comment by rck** [comment]
user does not care to provide a minimal example that would  at least compile, closing this as "does not reproduce".
