### ISSUE TITLE
Unable to modify storage pools

### ISSUE THREAD

**Issue by bencoxford** [LINBIT/golinstor#14]
Hi,

I am hitting an error trying to modify a storage pool:
```
time="2022-03-29T08:15:46Z" level=warning msg="Message: 'Method 'POST' not allowed on path '/v1/nodes/<node_name>/storage-pools/<sp_name>'.'; Details: 'HTTP 405 Method Not Allowed'"
```
Here is the line of code causing the error: https://github.com/LINBIT/golinstor/blob/f1d245ad162acd002f32bde56f31939d59cd783f/client/node.go#L285
It is sending a POST request to a path that [should be a PUT request](https://app.swaggerhub.com/apis-docs/Linstor/Linstor/1.13.0#/developers/nodeStoragePoolModify). The API is expecting the properties json to be passed as the body e.g.
```json
{
  "override_props": {
    "Aux/testprop": "1"
  },
  "delete_props": [
    "Aux/deleteprop"
  ]
}
```

Happy to take a look at this.

**Comment by rck** [comment]
Yes, confirmed and I come to the same conclusion, the POST should be a PUT. If you are willing to fix that, that would be great.
