### ISSUE TITLE
Support for linstor+ssl in url scheme

### ISSUE THREAD

**Issue by beornf** [LINBIT/golinstor#16]
I am working on completing the issue https://github.com/beornf/linstor-docker-volume/issues/19. I found there is a small difference in this library and the python API in that there only seems to be support for the `linstor` url scheme. See the code below:

https://github.com/LINBIT/golinstor/blob/d9b70593a298cc4acd57c883ecfcddb796b74465/client/client.go#L329-L332

A possible solution would be adding a check such as:
```go
if scheme == "linstor+ssl" {
	scheme = "https"
}
```
Let me know your thoughts.

**Comment by rck** [comment]
This library is nowadays mainly maintained/used by @chrboe and @WanzenBug , adding them to get their opinion, IMO such a compat check would not hurt...

**Comment by WanzenBug** [comment]
Sure, we can add that. I personally find the `linstor:` scheme generally weird, but it also does not hurt to add it here.

**Comment by chrboe** [comment]
Done in #17
