### ISSUE TITLE
Is it possible to change license from GPLv2 to MIT or Apache 2?

### ISSUE THREAD

**Issue by oneumyvakin** [LINBIT/golinstor#5]
Hello, 

currently this repository using GPLv2 License. Is it possible to change license from GPLv2 to MIT or Apache 2?

For example, CEPH Go client has MIT License: https://github.com/ceph/go-ceph/blob/master/LICENSE

**Comment by deleteriousEffect** [comment]
Could you provide some feedback on why you'd like the license to be different? Does it only have to be MIT or Apache2 to meet your needs?

**Comment by oneumyvakin** [comment]
@deleteriousEffect 

Currently I'm researching for ways to integrate proprietary solution with such SDS like Linstor and CEPH. 
We are using Go and I'd like to have native Go client for integration. 
Now I can't use your client because I've to compile client with our closed source code which require us to have GPL license and open source code what we can't do.

License can be any license which allows static linking without requirement to disclose source code and have same license. I've mention MIT and Apache 2.0 because this licenses are allowed to use in my company.

If license can't be changed it's ok, but for us it means that we have to create and maintain our own implementation of client.

**Comment by deleteriousEffect** [comment]
@Philipp-Reisner I'll defer this to you. I'll relicense it to whatever you decide.

**Comment by Philipp-Reisner** [comment]
As this is the client library I am find with licensing it under the terms of Apache2
